
tasks:
  - before: printf "\n[settings]\napi_key = $WAKATIME_API_KEY\n" > ~/.wakatime.cfg
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-french
    - ecrax.emoji-toolbox
    - wakatime.vscode-wakatime
